// writ a programto demonstrate a division by 0 exception.
public class DivideByZero {

	public static void main(String[] args) {
		try {
			int i=1/0;
			System.out.println(i);
		}catch(ArithmeticException ex)
		{
			System.out.println(" Exception caught inside catch block" +ex.getMessage());
		}
	}

}
